const { PRODUCTS } = await import("@nivora/shared/data/products");
const V = await import("@nivora/shared/domain/variantSelection");
let fail = 0; const ok = (c, m) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) fail++; };
const P = (slug) => PRODUCTS.find(p => p.slug === slug);
const shirt = P("urbano-classic-oxford-shirt");
ok(JSON.stringify(V.initialSelection(shirt)) === "{}" && V.missingOption(shirt, {}) === "Color", "multi-value options are not preselected; first missing option is Color");
ok(V.missingOption(shirt, { Color: "White" }) === "Size", "after choosing a colour, Size is the missing option ('Please select a size.')");
ok(!V.valueState(shirt, { Color: "White" }, "Size", "XXL").inStock && V.valueState(shirt, { Color: "Sky Blue" }, "Size", "XXL").inStock, "White/XXL disabled (out of stock) while Sky Blue/XXL is available");
ok(V.stockFor(shirt, { Color: "Sky Blue", Size: "S" }) === 2 && V.selectedVariant(shirt, { Color: "Sky Blue", Size: "S" })?.id === "urbano-classic-oxford-shirt-sky-blue-s", "full selection resolves the variant and its stock (Only 2 left)");
const kaftan = P("saanjh-printed-kaftan");
ok(V.initialSelection(kaftan).Size === "Free Size", "single-value option (Free Size) is preselected");
const op = P("oneplus-12r");
ok(!V.valueState(op, { RAM: "8 GB" }, "Storage", "256 GB").exists && !V.valueState(op, { RAM: "8 GB" }, "Storage", "256 GB").inStock && V.valueState(op, { RAM: "16 GB" }, "Storage", "256 GB").inStock, "OnePlus: 8 GB + 256 GB doesn't exist → unavailable; 16 GB + 256 GB available");
const s24 = P("samsung-galaxy-s24-ultra");
ok(V.priceFor(s24, {}).price === 129999 && V.priceFor(s24, {}).isRange, "S24 Ultra before selection: From ₹1,29,999");
ok(V.priceFor(s24, { Color: "Titanium Gray", RAM: "12 GB", Storage: "512 GB" }).price === 139999 && !V.priceFor(s24, { Color: "Titanium Gray", RAM: "12 GB", Storage: "512 GB" }).isRange, "choosing 512 GB updates the price to ₹1,39,999");
const realme = P("realme-narzo-70-pro-5g");
ok(V.stockFor(realme, V.initialSelection(realme)) === 0, "fully out-of-stock product → stock 0 (purchase disabled)");
const adj = { "urbano-classic-oxford-shirt-sky-blue-m": -25 };
ok(!V.valueState(shirt, { Color: "Sky Blue" }, "Size", "M", adj).inStock, "live stock adjustments disable a sold-out size");
ok(V.clampQuantity(5, 2) === 2 && V.clampQuantity(0, 10) === 1 && V.clampQuantity(3, 0) === 1, "quantity clamps to 1…stock when the variant changes");
console.log(fail ? `${fail} FAILED` : "ALL PASS");
