await import("./browser-shim.mjs");
const { mockWishlist: wl } = await import("@/api/client/mock/wishlist");
const { mockAddresses: addr } = await import("@/api/client/mock/addresses");
const { mockAuth: auth } = await import("@/api/client/mock/auth");
const { mockCart: cart } = await import("@/api/client/mock/cart");
const { adjustStock } = await import("@/api/client/mock/inventory");
let fail = 0; const ok = (c, m) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) fail++; };
const err = async (p) => { try { await p; return "OK"; } catch (e) { return e.code + (e.details?.fields ? " " + Object.values(e.details.fields).join("; ") : ""); } };
ok((await err(wl.getWishlist())) === "UNAUTHENTICATED" && (await err(wl.add("apple-iphone-15"))) === "UNAUTHENTICATED" && (await err(addr.list())) === "UNAUTHENTICATED", "guest calls to wishlist and addresses → UNAUTHENTICATED");
await auth.login({ email: "joseph@example.com", password: "password123" });
await wl.add("apple-iphone-15"); await wl.add("apple-iphone-15"); await wl.add("urbano-classic-oxford-shirt");
let w = await wl.getWishlist(); ok(w.length === 2 && w[0].name === "Apple iPhone 15" && typeof w[0].price === "number", "adding twice leaves one entry; returns product summaries");
ok((await err(wl.add("does-not-exist"))) === "NOT_FOUND", "unknown product → NOT_FOUND");
await wl.moveToCart({ productId: "urbano-classic-oxford-shirt", variantId: "urbano-classic-oxford-shirt-white-m" });
w = await wl.getWishlist(); const c = await cart.getCart();
ok(w.length === 1 && c.lines.some(l => l.variantId === "urbano-classic-oxford-shirt-white-m"), "move to cart: added to cart (qty 1) and removed from wishlist");
ok((await err(wl.moveToCart({ productId: "apple-iphone-15", variantId: "urbano-classic-oxford-shirt-white-m" }))) === "INVALID_VARIANT", "variant from another product → INVALID_VARIANT");
await wl.add("realme-narzo-70-pro-5g");
ok((await err(wl.moveToCart({ productId: "realme-narzo-70-pro-5g", variantId: "realme-narzo-70-pro-5g-glass-green-8-gb-128-gb" }))) === "OUT_OF_STOCK" && (await wl.getWishlist()).length === 2, "out-of-stock product can't be moved and stays in the wishlist");
await wl.remove("realme-narzo-70-pro-5g"); ok((await wl.getWishlist()).length === 1, "remove from wishlist");
await auth.logout(); await auth.login({ email: "joseph@example.com", password: "password123" }); ok((await wl.getWishlist()).length === 1, "wishlist persists across logout/login");
// addresses
const good = { fullName: "Joseph", phone: "9876543210", line1: "42, 3rd Cross", line2: "", city: "Bengaluru", state: "Karnataka", postalCode: "560038", country: "India" };
ok((await err(addr.create({ ...good, postalCode: "000000" }))).includes("Please enter a valid 6-digit PIN code.") && (await err(addr.create({ ...good, phone: "12345" }))).startsWith("INVALID_ADDRESS"), "invalid PIN / phone → INVALID_ADDRESS with field messages");
const a1 = await addr.create(good); const a2 = await addr.create({ ...good, line1: "7 MG Road", city: "Mysuru", postalCode: "570001" });
ok(a1.isDefault && !a2.isDefault && a1.line2 === undefined, "first address becomes the default; empty line 2 dropped");
await addr.setDefault(a2.id); let list = await addr.list();
ok(list[0].id === a2.id && list[0].isDefault && list.filter(a => a.isDefault).length === 1, "set default: exactly one default, listed first");
const upd = await addr.update(a1.id, { ...good, city: "Bangalore" }); ok(upd.city === "Bangalore" && !upd.isDefault, "edit keeps id and default flag");
await addr.remove(a2.id); list = await addr.list(); ok(list.length === 1 && list[0].isDefault, "deleting the default promotes the remaining address");
ok((await err(addr.update("nope", good))) === "NOT_FOUND" && (await err(addr.remove("nope"))) === "NOT_FOUND", "unknown address id → NOT_FOUND");
await auth.logout(); await auth.signup({ name: "New", email: "new@example.com", password: "password123", confirmPassword: "password123" });
ok((await addr.list()).length === 0 && (await wl.getWishlist()).length === 0, "another user sees only their own (empty) addresses and wishlist");
console.log(fail ? `${fail} FAILED` : "ALL PASS");
