const L = await import("@nivora/shared/domain/listingParams");
const F = await import("@/features/catalog/filterConfig");
let fail = 0; const ok = (c, m) => { console.log((c ? "PASS " : "FAIL ") + m); if (!c) fail++; };
const sp = (s) => new URLSearchParams(s);
const ctxMen = { categoryId: "fashion", subcategoryId: "fashion-men" };
const a = "brand=Levis,Urbano&size=M,L&price=500-2000&rating=4&discount=25&instock=1&sort=price-asc&page=2";
const q = L.parseListingParams(sp(a), ctxMen);
ok(q.categoryId === "fashion" && q.subcategoryIds[0] === "fashion-men" && q.brands.join() === "Levis,Urbano" && q.attributes.size.join() === "M,L" && q.priceMin === 500 && q.priceMax === 2000 && q.minRating === 4 && q.minDiscount === 25 && q.inStockOnly && q.sort === "price-asc" && q.page === 2, "arch §13.3 category URL parses into the right query");
ok(L.serialiseListingParams(q, ctxMen) === "brand=Levis,Urbano&size=M,L&price=500-2000&rating=4&discount=25&instock=1&sort=price-asc&page=2", "…and serialises back to the same canonical parameters");
const b = L.parseListingParams(sp("q=wireless+earbuds&category=mobiles&sort=rating"));
ok(b.q === "wireless earbuds" && b.categoryIds.join() === "mobiles" && b.sort === "rating" && L.serialiseListingParams(b) === "q=wireless+earbuds&category=mobiles&sort=rating", "arch §13.3 search URL round-trips");
const junk = L.parseListingParams(sp("sort=cheapest&page=-3&rating=7&discount=33&price=abc&instock=yes&category=cars,toys&evil=1&sub=../x"));
ok(junk.sort === "relevance" && junk.page === 1 && junk.minRating === undefined && junk.minDiscount === undefined && junk.priceMin === undefined && !junk.inStockOnly && junk.categoryIds.join() === "toys" && junk.subcategoryIds === undefined && L.serialiseListingParams(junk) === "category=toys", "garbage values and unknown params are ignored");
ok(L.parseListingParams(sp("price=2000-500")).priceMax === undefined && L.parseListingParams(sp("price=-999")).priceMax === 999 && L.parseListingParams(sp("price=50000-")).priceMin === 50000, "open-ended and inverted price ranges");
ok(L.parseListingParams({ size: ["S", "M"], brand: "A" }).attributes.size.join() === "S", "plain-object params (Next searchParams) supported");
const changed = L.withChange(q, { brands: ["Urbano"] });
ok(changed.page === 1 && changed.brands.join() === "Urbano", "changing a filter resets page to 1");
const cleared = L.clearRefinements({ ...q, q: "shirt" }, ctxMen);
ok(L.serialiseListingParams(cleared, ctxMen) === "q=shirt&sort=price-asc" && cleared.subcategoryIds[0] === "fashion-men", "Clear all keeps q, sort and the category path");
ok(L.hasRefinements(q, ctxMen) && !L.hasRefinements(cleared, ctxMen), "hasRefinements detects active filters");
const col = { collection: "new-arrivals", defaultSort: "newest" };
ok(L.parseListingParams(sp(""), col).sort === "newest" && L.serialiseListingParams(L.parseListingParams(sp(""), col), col) === "", "collection default sort is implicit (not written to the URL)");
ok(F.CATEGORY_FILTERS.fashion.join() === "size,color,brand,price,rating,discount,availability" && F.CATEGORY_FILTERS.mobiles.slice(0,3).join() === "brand,ram,storage" && F.CATEGORY_FILTERS["home-appliances"].slice(0,3).join() === "brand,capacity,energyRating" && F.CATEGORY_FILTERS.beauty.includes("skinHairType") && F.CATEGORY_FILTERS.toys.includes("ageGroup"), "category filter config matches arch §13.2 (Fashion, Mobiles, Home Appliances, Beauty, Toys)");
ok(F.crossCategoryFilters(null).join() === "category,subcategory,brand,price,rating,discount,availability" && F.crossCategoryFilters("mobiles").join() === "category,subcategory,brand,ram,storage,price,rating,discount,availability", "search/collection filters gain category-specific ones within a single category");
console.log(fail ? `${fail} FAILED` : "ALL PASS");
